### ISSUE TITLE
TypeError: Expected a plugin class, but got undefined

### ISSUE THREAD

**Issue by brunopopf** [imagekit-developer/imagekit-uppy-plugin#1]
Hi!

I tried to implement the basic example and I had some issues.

I am using React and yarn to add the imagekit-uppy-plugin. 

This is the error I am getting: 

![image](https://user-images.githubusercontent.com/52755231/100775912-2f1ee700-3404-11eb-8009-cd5b1c716f7c.png)

Any help on how to fix it? Thanks a lot!

**Comment by eco-line** [comment]
Hi @brunopopf 

This is the case where the plugin is not imported correctly.

You need to import it like this `import ImageKitUppyPlugin from "imagekit-uppy-plugin"` and not like this `import {ImageKitUppyPlugin} from "imagekit-uppy-plugin"`

If this doesn't solve your problem, please share the code where you are initializing and using the Imagekit plugin.

**Comment by brunopopf** [comment]
@vaibhavbansal23 It was the brackets! I thought I have tried it before! Thank you so much :)
